#ifdef _WIN32
  #define WIN32_LEAN_AND_MEAN
  #include <windows.h>
  #include <winsock2.h>
  #include <ws2tcpip.h>    /* gai_strerror() */
  #include <io.h>          /* write() */
  #include <fcntl.h>       /* O_BINARY */
#else
  #include <sys/socket.h>
  #include <netinet/in.h>
  #include <netdb.h>
  #include <arpa/inet.h>
  #include <unistd.h>
  #include <fcntl.h>
#endif

#include <sys/types.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>

#ifdef _WIN32
  #define sleep(s)        Sleep (1000*(s))
  #define read(s, buf, n) recv (s, buf, n, 0)
  #define close(s)        closesocket(s)
  #define bzero(buf, n)   memset(buf, '\0', n)

  /* Hacks for 'errno' stuff
   */
  #undef  EAGAIN
  #define EAGAIN       WSAEWOULDBLOCK
  #undef  EWOULDBLOCK
  #define EWOULDBLOCK  WSAEWOULDBLOCK
  #undef  errno
  #define errno        WSAGetLastError()
  #define perror(str)  fprintf(stderr, str ": %d.\n", WSAGetLastError())
  #define strerror(e)  ws_strerror(e)
  #ifndef STDOUT_FILENO
  #define STDOUT_FILENO 1  /* MinGW has this */
  #endif
#endif

/* crustls.h is autogenerated in the Makefile using cbindgen. */
#include "crustls.h"
#include "common.h"

/*
 * Connect to the given hostname on the given port and return the file descriptor of
 * the socket. On error, print the error and return 1. Caller is responsible
 * for closing socket.
 */
int
make_conn(const char *hostname, const char* port)
{
  int sockfd = 0;
  enum crustls_demo_result result = 0;
  struct addrinfo *getaddrinfo_output = NULL, hints;

  memset(&hints, 0, sizeof(hints));
  hints.ai_family = AF_UNSPEC;
  hints.ai_socktype = SOCK_STREAM; /* looking for TCP */

  fprintf(stderr, "connecting to %s:%s\n", hostname, port);
  int getaddrinfo_result =
    getaddrinfo(hostname, port, &hints, &getaddrinfo_output);
  if(getaddrinfo_result != 0) {
    fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(getaddrinfo_result));
    goto cleanup;
  }

  sockfd = socket(getaddrinfo_output->ai_family,
                  getaddrinfo_output->ai_socktype,
                  getaddrinfo_output->ai_protocol);
  if(sockfd < 0) {
    perror("making socket");
    goto cleanup;
  }

  int connect_result = connect(
    sockfd, getaddrinfo_output->ai_addr, getaddrinfo_output->ai_addrlen);
  if(connect_result < 0) {
    perror("connecting");
    goto cleanup;
  }
  result = nonblock(sockfd);
  if(result != CRUSTLS_DEMO_OK) {
    return 1;
  }

  freeaddrinfo(getaddrinfo_output);
  return sockfd;

cleanup:
  if(getaddrinfo_output != NULL) {
    freeaddrinfo(getaddrinfo_output);
  }
  if(sockfd > 0) {
    close(sockfd);
  }
  return -1;
}


/* Read all available bytes from the rustls_connection until EOF.
 * Note that EOF here indicates "no more bytes until
 * process_new_packets", not "stream is closed".
 *
 * Returns CRUSTLS_DEMO_OK for success,
 * CRUSTLS_DEMO_ERROR for error,
 * CRUSTLS_DEMO_CLOSE_NOTIFY for "received close_notify"
 */
int
copy_plaintext_to_stdout(struct rustls_connection *client_conn)
{
  int result;
  char buf[2048];
  size_t n;

  for(;;) {
    bzero(buf, sizeof(buf));
    result = rustls_connection_read(
      client_conn, (uint8_t *)buf, sizeof(buf), &n);
    if(result == RUSTLS_RESULT_ALERT_CLOSE_NOTIFY) {
      fprintf(stderr, "Received close_notify, cleanly ending connection\n");
      return CRUSTLS_DEMO_CLOSE_NOTIFY;
    }
    if(result != RUSTLS_RESULT_OK) {
      fprintf(stderr, "Error in rustls_connection_read: %d\n", result);
      return CRUSTLS_DEMO_ERROR;
    }
    if(n == 0) {
      /* This is expected. It just means "no more bytes for now." */
      return CRUSTLS_DEMO_OK;
    }

    result = write_all(STDOUT_FILENO, buf, n);
    if(result != 0) {
      return CRUSTLS_DEMO_ERROR;
    }
  }

  fprintf(stderr, "copy_plaintext_to_stdout: fell through loop\n");
  return CRUSTLS_DEMO_ERROR;
}

/*
 * Do one read from the socket, and process all resulting bytes into the
 * rustls_connection, then copy all plaintext bytes from the session to stdout.
 * Returns:
 *  - CRUSTLS_DEMO_OK for success
 *  - CRUSTLS_DEMO_AGAIN if we got an EAGAIN or EWOULDBLOCK reading from the
 *    socket
 *  - CRUSTLS_DEMO_EOF if we got EOF
 *  - CRUSTLS_DEMO_ERROR for other errors.
 */
enum crustls_demo_result
do_read(struct conndata_t *conn, struct rustls_connection *rconn)
{
  int err = 1;
  int result = 1;
  size_t n = 0;

  err = rustls_connection_read_tls(rconn, read_cb, conn, &n);

  if(err == EAGAIN || err == EWOULDBLOCK) {
    fprintf(stderr,
            "reading from socket: EAGAIN or EWOULDBLOCK: %s\n",
            strerror(errno));
    return CRUSTLS_DEMO_AGAIN;
  }
  else if(err != 0) {
    fprintf(stderr, "reading from socket: errno %d\n", err);
    return CRUSTLS_DEMO_ERROR;
  }

  result = rustls_connection_process_new_packets(rconn);
  if(result != RUSTLS_RESULT_OK) {
    print_error("in process_new_packets", result);
    return CRUSTLS_DEMO_ERROR;
  }

  result = copy_plaintext_to_buffer(conn);
  if(result != CRUSTLS_DEMO_CLOSE_NOTIFY) {
    return result;
  }

  char buf[2048];
  /* If we got a close_notify, verify that the sender then
   * closed the TCP connection. */
  n = recv(conn->fd, buf, sizeof(buf), 0);
  if(n != 0 && errno != EWOULDBLOCK) {
    fprintf(stderr, "read returned %ld after receiving close_notify: %s\n", n, strerror(errno));
    return CRUSTLS_DEMO_ERROR;
  }
  return CRUSTLS_DEMO_CLOSE_NOTIFY;
}

/*
 * Given an established TCP connection, and a rustls_connection, send an
 * HTTP request and read the response. On success, return 0. On error, print
 * the message and return 1.
 */
int
send_request_and_read_response(struct conndata_t *conn,
                               struct rustls_connection *rconn,
                               const char *hostname, const char *path)
{
  int sockfd = conn->fd;
  int ret = 1;
  int err = 1;
  int result = 1;
  char buf[2048];
  fd_set read_fds;
  fd_set write_fds;
  size_t n = 0;
  const char *body, *contentlengthstr, *contentlengthend;
  unsigned long contentlength;
  size_t headerslen = 0;

  bzero(buf, sizeof(buf));
  snprintf(buf,
           sizeof(buf),
           "GET %s HTTP/1.1\r\n"
           "Host: %s\r\n"
           "User-Agent: crustls-demo\r\n"
           "Accept: carcinization/inevitable, text/html\r\n"
           "Connection: close\r\n"
           "\r\n",
           path,
           hostname);
  result = rustls_connection_write(
    rconn, (uint8_t *)buf, strlen(buf), &n);
  if(result != RUSTLS_RESULT_OK) {
    fprintf(stderr, "error writing plaintext bytes to rustls_connection\n");
    goto cleanup;
  }
  if(n != strlen(buf)) {
    fprintf(stderr, "short write writing plaintext bytes to rustls_connection\n");
    goto cleanup;
  }

  for(;;) {
    FD_ZERO(&read_fds);
    if (rustls_connection_wants_read(rconn)) {
      FD_SET(sockfd, &read_fds);
    }
    FD_ZERO(&write_fds);
    if (rustls_connection_wants_write(rconn)) {
      FD_SET(sockfd, &write_fds);
    }

    result = select(sockfd + 1, &read_fds, &write_fds, NULL, NULL);
    if(result == -1) {
      perror("select");
      goto cleanup;
    }

    if(FD_ISSET(sockfd, &read_fds)) {
      fprintf(stderr,
              "rustls_connection wants us to read_tls. First we need to pull some "
              "bytes from the socket\n");

      /* Read all bytes until we get EAGAIN. Then loop again to wind up in
         select awaiting the next bit of data. */
      for(;;) {
        result = do_read(conn, rconn);
        if(result == CRUSTLS_DEMO_AGAIN) {
          break;
        }
        else if(result == CRUSTLS_DEMO_CLOSE_NOTIFY) {
          ret = 0;
          goto cleanup;
        }
        else if(result != CRUSTLS_DEMO_OK) {
          goto cleanup;
        }
        if(headerslen == 0) {
          body = body_begin(&conn->data);
          if(body != NULL) {
            headerslen = body - conn->data.data;
            fprintf(stderr, "body began at %ld\n", headerslen);
            contentlengthstr = get_first_header_value(conn->data.data, headerslen,
              "Content-Length", &n);
            if(contentlengthstr == NULL) {
              fprintf(stderr, "content length header not found\n");
              goto cleanup;
            }
            contentlength = strtoul(contentlengthstr, (char**)&contentlengthend, 10);
            if(contentlengthend == contentlengthstr) {
              fprintf(stderr, "invalid Content-Length '%.*s'\n", (int)n, contentlengthstr);
              goto cleanup;
            }
            fprintf(stderr, "content length %ld\n", contentlength);
          }
        }
        if(headerslen != 0 && conn->data.len >= headerslen + contentlength) {
          /* body is done. */
          write(STDERR_FILENO, conn->data.data, conn->data.len);
          ret = 0;
          goto cleanup;
        }
      }
    }
    if(FD_ISSET(sockfd, &write_fds)) {
      fprintf(stderr, "rustls_connection wants us to write_tls.\n");
      for(;;) {
        err = rustls_connection_write_tls(rconn, write_cb, conn, &n);
        if(err != 0) {
          fprintf(stderr, "Error in rustls_connection_write_tls: errno %d\n", err);
          goto cleanup;
        }
        if(result == CRUSTLS_DEMO_AGAIN) {
          break;
        }
        else if(n == 0) {
          fprintf(stderr, "write 0 from rustls_connection_write_tls\n");
          break;
        }
      }
    }
  }

  fprintf(stderr, "send_request_and_read_response: loop fell through");

cleanup:
  if(sockfd > 0) {
    close(sockfd);
  }
  return ret;
}

int
do_request(const struct rustls_client_config *client_config,
           const char *hostname, const char *port, const char *path)
{
  struct rustls_connection *rconn = NULL;
  struct conndata_t *conn = NULL;
  int ret = 1;
  int sockfd = make_conn(hostname, port);
  if(sockfd < 0) {
    // No perror because make_conn printed error already.
    goto cleanup;
  }

  rustls_result result =
    rustls_client_connection_new(client_config, hostname, &rconn);
  if(result != RUSTLS_RESULT_OK) {
    print_error("client_connection_new", result);
    goto cleanup;
  }

  conn = calloc(1, sizeof(struct conndata_t));
  if(conn == NULL) {
    goto cleanup;
  }
  conn->rconn = rconn;
  conn->fd = sockfd;
  conn->verify_arg = "verify_arg";

  rustls_connection_set_userdata(rconn, conn);

  ret = send_request_and_read_response(conn, rconn, hostname, path);
  if(ret != RUSTLS_RESULT_OK) {
    goto cleanup;
  }

  ret = 0;

cleanup:
  rustls_connection_free(rconn);
  if(sockfd > 0) {
    close(sockfd);
  }
  free(conn);
  return ret;
}

enum rustls_result
verify(void *userdata, const rustls_verify_server_cert_params *params) {
  size_t i = 0;
  const rustls_slice_slice_bytes *intermediates = params->intermediate_certs_der;
  struct rustls_slice_bytes bytes;
  const size_t intermediates_len = rustls_slice_slice_bytes_len(intermediates);
  struct conndata_t *conn = (struct conndata_t*)userdata;

  fprintf(stderr, "custom certificate verifier called for %.*s\n",
    (int)params->dns_name.len, params->dns_name.data);
  fprintf(stderr, "end entity len: %ld\n", params->end_entity_cert_der.len);
  fprintf(stderr, "intermediates:\n");
  for(i = 0; i<intermediates_len; i++) {
    bytes = rustls_slice_slice_bytes_get(intermediates, i);
    if(bytes.data != NULL) {
      fprintf(stderr, "  intermediate, len = %ld\n", bytes.len);
    }
  }
  fprintf(stderr, "ocsp response len: %ld\n", params->ocsp_response.len);
  if(0 != strcmp(conn->verify_arg, "verify_arg")) {
    fprintf(stderr, "invalid argument to verify: %p\n", userdata);
    return RUSTLS_RESULT_GENERAL;
  }
  return RUSTLS_RESULT_OK;
}

int
main(int argc, const char **argv)
{
  int ret = 1;
  int result = 1;
  if(argc <= 2) {
    fprintf(stderr,
            "usage: %s hostname port path\n\n"
            "Connect to a host via HTTPS on the provided port, make a request for the\n"
            "given path, and emit response to stdout (three times).\n",
            argv[0]);
    return 1;
  }
  const char *hostname = argv[1];
  const char *port = argv[2];
  const char *path = argv[3];

  struct rustls_client_config_builder *config_builder =
    rustls_client_config_builder_new();
  const struct rustls_client_config *client_config = NULL;
  const struct rustls_slice_bytes alpn_http11 = { (const uint8_t *)"http/1.1", 8 };
  const char *ca_file = "/etc/ssl/certs/ca-certificates.crt";


#ifdef _WIN32
  WSADATA wsa;
  WSAStartup (MAKEWORD(1,1), &wsa);
  setmode(STDOUT_FILENO, O_BINARY);
#endif

  if(getenv("CA_FILE")) {
    ca_file = getenv("CA_FILE");
  }

  result = rustls_client_config_builder_load_roots_from_file(config_builder, ca_file);
  if(result != RUSTLS_RESULT_OK) {
    print_error("loading trusted certificate", result);
    goto cleanup;
}
  if(getenv("NO_CHECK_CERTIFICATE")) {
    rustls_client_config_builder_dangerous_set_certificate_verifier(config_builder, verify);
  }

  rustls_client_config_builder_set_protocols(config_builder, &alpn_http11, 1);

  client_config = rustls_client_config_builder_build(config_builder);

  int i;
  for(i = 0; i < 3; i++) {
    result = do_request(client_config, hostname, port, path);
    if(result != 0) {
      goto cleanup;
    }
  }

  // Success!
  ret = 0;

cleanup:
  rustls_client_config_free(client_config);

#ifdef _WIN32
  WSACleanup();
#endif

  return ret;
}
