#include <sys/socket.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <netdb.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <arpa/inet.h>
#include <fcntl.h>

/* crustls.h is autogenerated in the Makefile using cbindgen. */
#include "crustls.h"

enum crustls_demo_result
{
  CRUSTLS_DEMO_OK,
  CRUSTLS_DEMO_ERROR,
  CRUSTLS_DEMO_AGAIN,
  CRUSTLS_DEMO_EOF,
};

/*
 * Write n bytes from buf to the provided fd, retrying short writes until
 * we finish or hit an error. Assumes fd is blocking and therefore doesn't
 * handle EAGAIN. Returns 0 for success or 1 for error.
 */
int
write_all(int fd, const char *buf, int n)
{
  int m = 0;
  while(n > 0) {
    m = write(fd, buf, n);
    if(m < 0) {
      perror("writing to stdout");
      return 1;
    }
    if(m == 0) {
      fprintf(stderr, "early EOF when writing to stdout\n");
      return 1;
    }
    n -= m;
  }
  return 0;
}

/*
 * Set a socket to be nonblocking.
 *
 * Returns CRUSTLS_DEMO_OK on success, CRUSTLS_DEMO_ERROR on error.
 */
enum crustls_demo_result
nonblock(int sockfd)
{
  int flags;
  flags = fcntl(sockfd, F_GETFL, 0);
  if(flags < 0) {
    perror("getting socket flags");
    return CRUSTLS_DEMO_ERROR;
  }
  flags = fcntl(sockfd, F_SETFL, flags | O_NONBLOCK);
  if(flags < 0) {
    perror("setting socket nonblocking");
    return CRUSTLS_DEMO_ERROR;
  }
  return CRUSTLS_DEMO_OK;
}

/*
 * Connect to the given hostname on port 443 and return the file descriptor of
 * the socket. On error, print the error and return 1. Caller is responsible
 * for closing socket.
 */
int
make_conn(const char *hostname)
{
  int sockfd = 0;
  enum crustls_demo_result result = 0;
  struct addrinfo *getaddrinfo_output = NULL;
  int getaddrinfo_result =
    getaddrinfo(hostname, "443", NULL, &getaddrinfo_output);
  if(getaddrinfo_result != 0) {
    fprintf(stderr, "getaddrinfo: %s\n", gai_strerror(getaddrinfo_result));
    goto cleanup;
  }

  sockfd = socket(getaddrinfo_output->ai_family,
                  getaddrinfo_output->ai_socktype,
                  getaddrinfo_output->ai_protocol);
  if(sockfd < 0) {
    perror("making socket");
    goto cleanup;
  }

  int connect_result = connect(
    sockfd, getaddrinfo_output->ai_addr, getaddrinfo_output->ai_addrlen);
  if(connect_result < 0) {
    perror("connecting");
    goto cleanup;
  }
  result = nonblock(sockfd);
  if(result != CRUSTLS_DEMO_OK) {
    return 1;
  }

  return sockfd;

cleanup:
  if(getaddrinfo_output != NULL) {
    freeaddrinfo(getaddrinfo_output);
  }
  if(sockfd > 0) {
    close(sockfd);
  }
  return -1;
}

/*
 * Copy all the ciphertext bytes from buf into the client session.
 * Returns 0 for success, 1 for error.
 */
int
copy_tls_bytes_into_client_session(
  struct rustls_client_session *client_session, uint8_t *buf, size_t len)
{
  ssize_t n;
  int result;

  while(len > 0) {
    n = rustls_client_session_read_tls(client_session, buf, len);
    if(n == 0) {
      fprintf(stderr, "EOF from ClientSession::read_tls %ld \n", len);
      return 1;
    }
    else if(n < 0) {
      fprintf(stderr, "Error in ClientSession::read_tls\n");
      return 1;
    }
    if((size_t)n > len) {
      fprintf(stderr, "too many bytes written to ClientSession; overflow\n");
      return 1;
    }
    len -= n;
    buf += n;

    result = rustls_client_session_process_new_packets(client_session);
    if(result != RUSTLS_RESULT_OK) {
      fprintf(stderr, "Error in process_new_packets\n");
      return 1;
    }
  }
  return 0;
}

/* Read all available bytes from the client_session until EOF.
 * Note that EOF here indicates "no more bytes until
 * process_new_packets", not "stream is closed".
 *
 * Returns 0 for success, 1 for error.
 */
int
copy_plaintext_to_stdout(struct rustls_client_session *client_session)
{
  int result = 1;
  char buf[2048];
  int n;

  for(;;) {
    bzero(buf, sizeof(buf));
    n =
      rustls_client_session_read(client_session, (uint8_t *)buf, sizeof(buf));
    if(n == 0) {
      /* EOF from ClientSession::read. This is expected. */
      return 0;
    }
    else if(n < 0) {
      fprintf(stderr, "Error in ClientSession::read\n");
      return 1;
    }

    result = write_all(STDOUT_FILENO, buf, n);
    if(result != 0) {
      return result;
    }
  }

  fprintf(stderr, "copy_plaintext_to_stdout: fell through loop\n");
  return 1;
}

/*
 * Do one read from the socket, and process all resulting bytes into the
 * client_session, then copy all plaintext bytes from the session to stdout.
 * Returns:
 *  - CRUSTLS_DEMO_OK for success
 *  - CRUSTLS_DEMO_AGAIN if we got an EAGAIN or EWOULDBLOCK reading from the
 *    socket
 *  - CRUSTLS_DEMO_EOF if we got EOF
 *  - CRUSTLS_DEMO_ERROR for other errors.
 */
enum crustls_demo_result
do_read(int sockfd, struct rustls_client_session *client_session)
{
  int result = 1;
  ssize_t n = 0;
  char buf[2048];

  bzero(buf, sizeof(buf));
  n = read(sockfd, buf, sizeof(buf));
  if(n == 0) {
    fprintf(stderr, "EOF reading from socket\n");
    return CRUSTLS_DEMO_EOF;
  }
  else if(n < 0) {
    if(errno == EAGAIN || errno == EWOULDBLOCK) {
      fprintf(stderr,
              "reading from socket: EAGAIN or EWOULDBLOCK: %s\n",
              strerror(errno));
      return CRUSTLS_DEMO_AGAIN;
    }
    else {
      perror("reading from socket");
      return CRUSTLS_DEMO_ERROR;
    }
  }

  /*
   * Now pull those bytes from the buffer into ClientSession.
   * Note that we pass buf, n; not buf, sizeof(buf). We don't
   * want to pull in unitialized memory that we didn't just
   * read from the socket.
   */
  result =
    copy_tls_bytes_into_client_session(client_session, (uint8_t *)buf, n);
  if(result != 0) {
    return CRUSTLS_DEMO_ERROR;
  }

  result = copy_plaintext_to_stdout(client_session);
  if(result != 0) {
    return CRUSTLS_DEMO_ERROR;
  }

  return CRUSTLS_DEMO_OK;
}

/*
 * Given an established TCP connection, and a rustls client_session, send an
 * HTTP request and read the response. On success, return 0. On error, print
 * the message and return 1.
 */
int
send_request_and_read_response(int sockfd,
                               struct rustls_client_session *client_session,
                               const char *hostname, const char *path)
{
  int ret = 1;
  int result = 1;
  char buf[2048];
  fd_set read_fds;
  fd_set write_fds;
  int n = 0;

  bzero(buf, sizeof(buf));
  snprintf(buf,
           sizeof(buf),
           "GET %s HTTP/1.1\r\n"
           "Host: %s\r\n"
           "User-Agent: crustls-demo\r\n"
           "Accept: carcinization/inevitable, text/html\r\n"
           "Connection: close\r\n"
           "\r\n",
           path,
           hostname);
  n = rustls_client_session_write(client_session, (uint8_t *)buf, strlen(buf));
  if(n < 0) {
    fprintf(stderr, "error writing plaintext bytes to ClientSession\n");
    goto cleanup;
  }

  for(;;) {
    FD_ZERO(&read_fds);
    FD_SET(sockfd, &read_fds);
    FD_ZERO(&write_fds);
    FD_SET(sockfd, &write_fds);

    result = select(sockfd + 1, &read_fds, &write_fds, NULL, NULL);
    if(result == -1) {
      perror("select");
      goto cleanup;
    }

    if(rustls_client_session_wants_read(client_session) &&
       FD_ISSET(sockfd, &read_fds)) {
      fprintf(stderr,
              "ClientSession wants us to read_tls. First we need to pull some "
              "bytes from the socket\n");

      /* Read all bytes until we get EAGAIN. Then loop again to wind up in
         select awaiting the next bit of data. */
      for(;;) {
        result = do_read(sockfd, client_session);
        if(result == CRUSTLS_DEMO_AGAIN) {
          break;
        }
        else if(result == CRUSTLS_DEMO_EOF) {
          ret = 0;
          goto cleanup;
        }
        else if(result != CRUSTLS_DEMO_OK) {
          goto cleanup;
        }
      }
    }
    if(rustls_client_session_wants_write(client_session) &&
       FD_ISSET(sockfd, &write_fds)) {
      fprintf(stderr, "ClientSession wants us to write_tls.\n");
      bzero(buf, sizeof(buf));
      n = rustls_client_session_write_tls(
        client_session, (uint8_t *)buf, sizeof(buf));
      if(n == 0) {
        fprintf(stderr, "EOF from ClientSession::write_tls\n");
        goto cleanup;
      }
      else if(n < 0) {
        fprintf(stderr, "Error in ClientSession::write_tls\n");
        goto cleanup;
      }

      result = write_all(sockfd, buf, n);
      if(result != 0) {
        goto cleanup;
      }
    }
  }

  fprintf(stderr, "send_request_and_read_response: loop fell through");

cleanup:
  if(sockfd > 0) {
    close(sockfd);
  }
  return ret;
}

int
do_request(const struct rustls_client_config *client_config,
           const char *hostname, const char *path)
{
  struct rustls_client_session *client_session = NULL;
  int ret = 1;
  int sockfd = make_conn(hostname);
  if(sockfd < 0) {
    // No perror because make_conn printed error already.
    goto cleanup;
  }

  rustls_result result =
    rustls_client_session_new(client_config, hostname, &client_session);
  if(result != RUSTLS_RESULT_OK) {
    goto cleanup;
  }

  ret = send_request_and_read_response(sockfd, client_session, hostname, path);
  if(ret != RUSTLS_RESULT_OK) {
    goto cleanup;
  }

  ret = 0;

cleanup:
  rustls_client_session_free(client_session);
  if(sockfd > 0) {
    close(sockfd);
  }
  return ret;
}

int
main(int argc, const char **argv)
{
  int ret = 1;
  int result = 1;
  if(argc <= 2) {
    fprintf(stderr,
            "usage: %s hostname path\n\n"
            "Connect to a host via HTTPS on port 443, make a request for the\n"
            "given path, and emit response to stdout.\n",
            argv[0]);
    return 1;
  }
  const char *hostname = argv[1];
  const char *path = argv[2];

  const struct rustls_client_config *client_config =
    rustls_client_config_new();

  int i;
  for(i = 0; i < 3; i++) {
    result = do_request(client_config, hostname, path);
    if(result != 0) {
      goto cleanup;
    }
  }

  // Success!
  ret = 0;

cleanup:
  rustls_client_config_free(client_config);
  return ret;
}
